# device: "cuda" | "cpu"
# mode 0: train the quantized neural network
# mode 1: train the binary neural network
# mode 2: train the full precision neural network
device: cuda
mode: 2

# hyperparameters and model type
# model:            "ternary"
# batch_size:       literal meaning
# tau:              number of local iterations
# momentum:         momentum settings for the optimizer
# qnn_model: "binary"
# qnn_model: "ternary"
# qnn_model: "tgn1"
qnn_model: "binary1"
# qnn_model: "binary_complete"
# qnn_model: "ternary_complete"
total_epoch: 20
batch_size: 256
lr: 0.0005
# lr: 0.1
# lr: 0.05
momentum: 0.9
weight_decay: 1.e-10
freeze_fc: true
# regularizer
lambda_: 0.1


# full precision model counterpart
full_model: "bn1"
# full_model: "gn1"
# full_model: "type2"
full_weight_dir: ""
# full_weight_dir: "checkpoints/fmnist_bn.pth"
# full_weight_dir: "/media/kaiyue/2D8A97B87FB4A806/Datasets/heuristic/full_init.pth"

# Simulation dataset configurations
# test_data_dir : the directory to the testDataset
# train_data_dir: the directory to the trainDataset
# sample_size:   the size of one sample [height x width\num_of_features]
# classes:      the number of classes
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/train.dat
test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/test.dat
train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/train.dat
sample_size:
- 28
- 28
channels: 1
classes: 10

record_dir:     ../This{}.dat
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/train.dat
# sample_size:
# - 32
# - 32
# channels: 3
# classes: 10


# Log configurations
log_iters:   100
log_level:   "INFO"
log_file:    "./train.log"