# device: "cuda" | "cpu"
# mode 0: train the quantized neural network
# mode 1: train the binary neural network
# mode 2: train the full precision neural network
device: cuda
mode: 0

# hyperparameters and model type
# model:            "ternary"
# batch_size:       literal meaning
# tau:              number of local iterations
# momentum:         momentum settings for the optimizer
# qnn_model: "binary"
qnn_model: "ternary"
total_epoch: 20
batch_size: 256
lr: 0.05
momentum: 0.9
weight_decay: 0
freeze_fc: true
# regularizer
lambda_: 0.1


# full precision model counterpart
full_model: "type1"
# full_weight_dir: "checkpoints/fmnist1.pth"
# full_weight_dir: "/media/kaiyue/2D8A97B87FB4A806/Projects/bnn/ternary_oldcheckpoints/checkpoints/mnist_bn3.pth"
full_weight_dir: ""

# Simulation dataset configurations
# test_data_dir : the directory to the testDataset
# train_data_dir: the directory to the trainDataset
# sample_size:   the size of one sample [height x width\num_of_features]
# classes:      the number of classes
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/mnist/train.dat
test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/test.dat
train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/fmnist/train.dat
sample_size:
- 28
- 28
channels: 1
classes: 10

# record_dir:     ../This{}.dat
# test_data_dir:  /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/test.dat
# train_data_dir: /media/kaiyue/2D8A97B87FB4A806/Datasets/cifar-10-python/train.dat
# sample_size:
# - 32
# - 32
# channels: 3
# classes: 10


# Log configurations
log_iters:   100
log_level:   "INFO"
log_file:    "./train.log"